spring:
  mvc:
    hidden-method:
      filter:
        enabled: true
  freemarker:
    cache: false
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            scope:
              - email
              - profile

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.ct9qwzzh9uwy.ap-northeast-2.rds.amazonaws.com:13306/main?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #jdbc:mysql://database-1.ct9qwzzh9uwy.ap-northeast-2.rds.amazonaws.com:13306/main?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #jdbc:mysql://localhost:3306/main?serverTimezone=Asia/Seoul
    username: admin
    password: qwer1234




mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes:  120
  refresh-token-expiration-minutes: 28800
logging.level:
  org:
    springframework:
      web.servlet: debug
server:
 servlet:
   encoding:
     force-response: true
