name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  
env:
  ECR_REGISTRY: <your_ecr_registry>
  ECR_REPOSITORY: <your_ecr_repository>
  IMAGE_TAG: latest

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
    - name: Build with Gradle
      run: ./gradlew build
    
    # Docker 이미지 빌드
    - name: Build Docker image
      run: docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
    
    # Docker 이미지 푸시
    - name: Push Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ env.ECR_REGISTRY }}
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
    
    # AWS CLI 설치 및 ECR 로그인
    - name: Install AWS CLI and login to ECR
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        aws ecr get-login-password --region <your_aws_region> | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}
    
    # Docker 이미지 푸시
    - name: Push Docker image to ECR
      run: |
        docker tag ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
